modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="breadcraft"
version="1.2.3"
displayName="Soot's Sandwichcraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://www.curseforge.com/minecraft/mc-mods/soots-sandwichcraft"
logoFile="logo.png"
authors="sootdude"
description="Soot's Sandwichcraft is a sandwich-making mod with 31 varieties of bread, 50 varieties of sandwiches, and plenty of side dishes."

[[dependencies.breadcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




